# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e19177535cf8b0ff3832a220977275c2a25df4a9f7706f053b0d16b4111fc3bd0e36714b7d5c77a9a51f0a225e109a99498f660865cbc40fd8e4b8509cd108f8

test:
  secret_key_base: 22538a7e0d5bed5b9f6efa704c25522980407f7d9f394fbb75d38c680a662f4c342e81478599fae8494cb05581e402621b8b4f14e23d28f34a0e3cc7c3470119

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: cc386323e4cc0619e268bfce54883387bcd664dc700f540da2b939c7ca6fdb90cb3301184c6d8b95747c8e251cb60e03630c8fca79705a41395278119866954e
  #secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
